const en = {
  title: "Bookmarks", empty: "No bookmarks yet. Save the place you are reading to come back to it later.", name: "Name", save: "Save bookmark", saved: "Bookmark saved",
  current: "Save current location", selection: "Save selection", location: "Reading location", range: "Selected passage",
  open: "Go to bookmark", rename: "Rename", renamed: "Bookmark renamed", remove: "Delete", removed: "Bookmark deleted",
  confirm: "Delete this bookmark", invalidName: "Enter a name of 1–120 characters.", required: "Confirm deletion first.",
  invalid: "Unreadable bookmark", missing: "This bookmark no longer exists.", stale: "Bookmarks changed. Reload the list.",
  conflict: "This bookmark changed in the meantime. Reload before trying again.", refresh: "Refresh", all: "All books", thisBook: "This book only",
  book: "Book", kind: "Type", savedAt: "Saved",
};
type Copy = typeof en;
const translations: Record<string, Copy> = {
  en,
  "zh-Hans": {
    title: "书签", empty: "还没有书签。保存正在读的位置，之后随时回来。", name: "名称", save: "保存书签", saved: "书签已保存",
    current: "保存当前位置", selection: "保存选中段落", location: "阅读位置", range: "选中段落",
    open: "跳转到书签", rename: "重命名", renamed: "书签已重命名", remove: "删除", removed: "书签已删除",
    confirm: "删除这条书签", invalidName: "请输入 1–120 个字符的名称。", required: "请先确认删除。",
    invalid: "无法读取的书签", missing: "这条书签已不存在。", stale: "书签列表已变化，请刷新。",
    conflict: "这条书签在此期间有变化，请刷新后再试。", refresh: "刷新", all: "全部书籍", thisBook: "仅当前书",
    book: "书籍", kind: "类型", savedAt: "保存于",
  },
  "zh-Hant": {
    title: "書籤", empty: "還沒有書籤。儲存正在讀的位置，之後隨時回來。", name: "名稱", save: "儲存書籤", saved: "書籤已儲存",
    current: "儲存目前位置", selection: "儲存選取段落", location: "閱讀位置", range: "選取段落",
    open: "跳轉到書籤", rename: "重新命名", renamed: "書籤已重新命名", remove: "刪除", removed: "書籤已刪除",
    confirm: "刪除這則書籤", invalidName: "請輸入 1–120 個字元的名稱。", required: "請先確認刪除。",
    invalid: "無法讀取的書籤", missing: "這則書籤已不存在。", stale: "書籤清單已變化，請重新整理。",
    conflict: "這則書籤在此期間有變化，請重新整理後再試。", refresh: "重新整理", all: "全部書籍", thisBook: "僅目前的書",
    book: "書籍", kind: "類型", savedAt: "儲存於",
  },
  ja: {
    title: "ブックマーク", empty: "ブックマークはまだありません。読んでいる場所を保存すると、あとで戻れます。", name: "名前", save: "ブックマークを保存", saved: "ブックマークを保存しました",
    current: "現在の位置を保存", selection: "選択範囲を保存", location: "読書位置", range: "選択した箇所",
    open: "ブックマークへ移動", rename: "名前を変更", renamed: "ブックマーク名を変更しました", remove: "削除", removed: "ブックマークを削除しました",
    confirm: "このブックマークを削除する", invalidName: "1〜120文字の名前を入力してください。", required: "先に削除を確認してください。",
    invalid: "読み取れないブックマーク", missing: "このブックマークはもう存在しません。", stale: "ブックマークが変わりました。一覧を再読み込みしてください。",
    conflict: "このブックマークはその間に変更されました。再読み込みしてやり直してください。", refresh: "更新", all: "すべての本", thisBook: "この本のみ",
    book: "本", kind: "種類", savedAt: "保存日時",
  },
  ru: {
    title: "Закладки", empty: "Закладок пока нет. Сохраните место, где вы читаете, чтобы вернуться к нему позже.", name: "Название", save: "Сохранить закладку", saved: "Закладка сохранена",
    current: "Сохранить текущее место", selection: "Сохранить выделение", location: "Место чтения", range: "Выделенный фрагмент",
    open: "Перейти к закладке", rename: "Переименовать", renamed: "Закладка переименована", remove: "Удалить", removed: "Закладка удалена",
    confirm: "Удалить эту закладку", invalidName: "Введите название длиной от 1 до 120 символов.", required: "Сначала подтвердите удаление.",
    invalid: "Нечитаемая закладка", missing: "Этой закладки больше нет.", stale: "Закладки изменились. Обновите список.",
    conflict: "Эта закладка тем временем изменилась. Обновите и попробуйте снова.", refresh: "Обновить", all: "Все книги", thisBook: "Только эта книга",
    book: "Книга", kind: "Тип", savedAt: "Сохранено",
  },
  fr: {
    title: "Signets", empty: "Aucun signet pour l’instant. Enregistrez l’endroit où vous lisez pour y revenir plus tard.", name: "Nom", save: "Enregistrer le signet", saved: "Signet enregistré",
    current: "Enregistrer la position actuelle", selection: "Enregistrer la sélection", location: "Position de lecture", range: "Passage sélectionné",
    open: "Aller au signet", rename: "Renommer", renamed: "Signet renommé", remove: "Supprimer", removed: "Signet supprimé",
    confirm: "Supprimer ce signet", invalidName: "Saisissez un nom de 1 à 120 caractères.", required: "Confirmez d’abord la suppression.",
    invalid: "Signet illisible", missing: "Ce signet n’existe plus.", stale: "Les signets ont changé. Rechargez la liste.",
    conflict: "Ce signet a changé entre-temps. Rechargez avant de réessayer.", refresh: "Actualiser", all: "Tous les livres", thisBook: "Ce livre seulement",
    book: "Livre", kind: "Type", savedAt: "Enregistré",
  },
  de: {
    title: "Lesezeichen", empty: "Noch keine Lesezeichen. Speichern Sie die Stelle, an der Sie lesen, um später dorthin zurückzukehren.", name: "Name", save: "Lesezeichen speichern", saved: "Lesezeichen gespeichert",
    current: "Aktuelle Stelle speichern", selection: "Auswahl speichern", location: "Leseposition", range: "Ausgewählte Textstelle",
    open: "Zum Lesezeichen", rename: "Umbenennen", renamed: "Lesezeichen umbenannt", remove: "Löschen", removed: "Lesezeichen gelöscht",
    confirm: "Dieses Lesezeichen löschen", invalidName: "Geben Sie einen Namen mit 1–120 Zeichen ein.", required: "Bestätigen Sie zuerst das Löschen.",
    invalid: "Unlesbares Lesezeichen", missing: "Dieses Lesezeichen existiert nicht mehr.", stale: "Die Lesezeichen haben sich geändert. Laden Sie die Liste neu.",
    conflict: "Dieses Lesezeichen hat sich inzwischen geändert. Laden Sie neu und versuchen Sie es erneut.", refresh: "Aktualisieren", all: "Alle Bücher", thisBook: "Nur dieses Buch",
    book: "Buch", kind: "Typ", savedAt: "Gespeichert",
  },
  es: {
    title: "Marcadores", empty: "Aún no hay marcadores. Guarda el lugar por el que vas para volver más tarde.", name: "Nombre", save: "Guardar marcador", saved: "Marcador guardado",
    current: "Guardar posición actual", selection: "Guardar selección", location: "Posición de lectura", range: "Pasaje seleccionado",
    open: "Ir al marcador", rename: "Renombrar", renamed: "Marcador renombrado", remove: "Eliminar", removed: "Marcador eliminado",
    confirm: "Eliminar este marcador", invalidName: "Escribe un nombre de 1 a 120 caracteres.", required: "Confirma primero la eliminación.",
    invalid: "Marcador ilegible", missing: "Este marcador ya no existe.", stale: "Los marcadores cambiaron. Recarga la lista.",
    conflict: "Este marcador cambió mientras tanto. Recarga antes de reintentar.", refresh: "Actualizar", all: "Todos los libros", thisBook: "Solo este libro",
    book: "Libro", kind: "Tipo", savedAt: "Guardado",
  },
};
export const bookmarkCopy = (locale: string): Copy =>
  translations[locale] ?? translations[locale.split("-")[0]!] ?? (locale.startsWith("zh") ? translations["zh-Hans"]! : en);
