const en = {
  title: "Reading Goals",
  goal: "What do you want to get out of this book?",
  goalPlaceholder: "Understand the author's main argument well enough to explain it to a friend.",
  goalHelp: "The assistant sees this goal whenever you chat inside this book.",
  remember: "Also suggest this goal for long-term memory",
  save: "Save goal",
  clear: "Clear goal",
  noBook: "Open a book to set a reading goal for it.",
  invalid: "Enter a goal of 1 to 500 characters.",
  refresh: "Refresh",
  saved: "Goal saved",
  cleared: "Goal cleared",
  conflict: "This goal changed elsewhere. Reload before trying again.",
  confirm: "Clear the reading goal for this book",
  required: "Confirm clearing first.",
  memoryOff: "Long-term memory is turned off in Settings → AI, so the goal will not be suggested for memory until you turn it on.",
  bookMissing: "This book is no longer in your library.",
};
type Copy = typeof en;
const copies: Record<string, Copy> = {
  en,
  "zh-Hans": {
    title: "阅读目标",
    goal: "你想从这本书里得到什么？",
    goalPlaceholder: "把作者的核心论点搞清楚，能讲给朋友听。",
    goalHelp: "在这本书里聊天时，助手会看到这个目标。",
    remember: "同时把这个目标推荐进长期记忆",
    save: "保存目标",
    clear: "清除目标",
    noBook: "打开一本书，再为它设定阅读目标。",
    invalid: "请输入 1 至 500 个字符的目标。",
    refresh: "刷新",
    saved: "目标已保存",
    cleared: "目标已清除",
    conflict: "这个目标在别处被修改了，请刷新后再试。",
    confirm: "清除这本书的阅读目标",
    required: "请先确认清除。",
    memoryOff: "长期记忆已在“设置 → AI”中关闭，打开之前不会推荐这个目标进记忆。",
    bookMissing: "这本书已不在你的书库中。",
  },
  "zh-Hant": {
    title: "閱讀目標",
    goal: "你想從這本書得到什麼？",
    goalPlaceholder: "把作者的核心論點弄清楚，能講給朋友聽。",
    goalHelp: "在這本書裡聊天時，助理會看到這個目標。",
    remember: "同時把這個目標推薦進長期記憶",
    save: "儲存目標",
    clear: "清除目標",
    noBook: "開啟一本書，再為它設定閱讀目標。",
    invalid: "請輸入 1 至 500 個字元的目標。",
    refresh: "重新整理",
    saved: "目標已儲存",
    cleared: "目標已清除",
    conflict: "這個目標在別處被修改了，請重新整理後再試。",
    confirm: "清除這本書的閱讀目標",
    required: "請先確認清除。",
    memoryOff: "長期記憶已在「設定 → AI」中關閉，開啟之前不會推薦這個目標進記憶。",
    bookMissing: "這本書已不在你的書庫中。",
  },
  ja: {
    title: "読書目標",
    goal: "この本から何を得たいですか？",
    goalPlaceholder: "著者の主張を友人に説明できるくらい理解する。",
    goalHelp: "この本の中でチャットするとき、アシスタントはこの目標を参照します。",
    remember: "この目標を長期メモリにも提案する",
    save: "目標を保存",
    clear: "目標を削除",
    noBook: "本を開いてから読書目標を設定してください。",
    invalid: "1〜500文字の目標を入力してください。",
    refresh: "更新",
    saved: "目標を保存しました",
    cleared: "目標を削除しました",
    conflict: "この目標は別の場所で変更されました。再読み込みしてやり直してください。",
    confirm: "この本の読書目標を削除する",
    required: "先に削除を確認してください。",
    memoryOff: "長期メモリは「設定 → AI」でオフになっています。オンにするまでこの目標はメモリに提案されません。",
    bookMissing: "この本はもうライブラリにありません。",
  },
  de: {
    title: "Leseziele",
    goal: "Was möchten Sie aus diesem Buch mitnehmen?",
    goalPlaceholder: "Das Hauptargument des Autors so gut verstehen, dass ich es einem Freund erklären kann.",
    goalHelp: "Der Assistent sieht dieses Ziel bei jedem Gespräch in diesem Buch.",
    remember: "Dieses Ziel auch für das Langzeitgedächtnis vorschlagen",
    save: "Ziel speichern",
    clear: "Ziel löschen",
    noBook: "Öffnen Sie ein Buch, um ein Leseziel dafür festzulegen.",
    invalid: "Geben Sie ein Ziel mit 1 bis 500 Zeichen ein.",
    refresh: "Aktualisieren",
    saved: "Ziel gespeichert",
    cleared: "Ziel gelöscht",
    conflict: "Dieses Ziel wurde anderswo geändert. Laden Sie neu und versuchen Sie es erneut.",
    confirm: "Das Leseziel für dieses Buch löschen",
    required: "Bestätigen Sie zuerst das Löschen.",
    memoryOff: "Das Langzeitgedächtnis ist unter Einstellungen → KI ausgeschaltet. Bis Sie es einschalten, wird das Ziel nicht für das Gedächtnis vorgeschlagen.",
    bookMissing: "Dieses Buch ist nicht mehr in Ihrer Bibliothek.",
  },
  fr: {
    title: "Objectifs de lecture",
    goal: "Que voulez-vous retirer de ce livre ?",
    goalPlaceholder: "Comprendre l’argument principal de l’auteur assez bien pour l’expliquer à un ami.",
    goalHelp: "L’assistant voit cet objectif à chaque conversation dans ce livre.",
    remember: "Proposer aussi cet objectif pour la mémoire à long terme",
    save: "Enregistrer l’objectif",
    clear: "Effacer l’objectif",
    noBook: "Ouvrez un livre pour lui définir un objectif de lecture.",
    invalid: "Saisissez un objectif de 1 à 500 caractères.",
    refresh: "Actualiser",
    saved: "Objectif enregistré",
    cleared: "Objectif effacé",
    conflict: "Cet objectif a été modifié ailleurs. Rechargez avant de réessayer.",
    confirm: "Effacer l’objectif de lecture de ce livre",
    required: "Confirmez d’abord l’effacement.",
    memoryOff: "La mémoire à long terme est désactivée dans Réglages → IA ; l’objectif ne sera pas proposé pour la mémoire tant qu’elle est désactivée.",
    bookMissing: "Ce livre n’est plus dans votre bibliothèque.",
  },
  es: {
    title: "Objetivos de lectura",
    goal: "¿Qué quieres sacar de este libro?",
    goalPlaceholder: "Entender el argumento principal del autor lo bastante bien como para explicárselo a un amigo.",
    goalHelp: "El asistente ve este objetivo cada vez que conversas dentro de este libro.",
    remember: "Proponer también este objetivo para la memoria a largo plazo",
    save: "Guardar objetivo",
    clear: "Borrar objetivo",
    noBook: "Abre un libro para fijarle un objetivo de lectura.",
    invalid: "Escribe un objetivo de 1 a 500 caracteres.",
    refresh: "Actualizar",
    saved: "Objetivo guardado",
    cleared: "Objetivo borrado",
    conflict: "Este objetivo cambió en otro lugar. Recarga antes de reintentar.",
    confirm: "Borrar el objetivo de lectura de este libro",
    required: "Confirma primero el borrado.",
    memoryOff: "La memoria a largo plazo está desactivada en Ajustes → IA; el objetivo no se propondrá para la memoria hasta que la actives.",
    bookMissing: "Este libro ya no está en tu biblioteca.",
  },
  ru: {
    title: "Цели чтения",
    goal: "Что вы хотите вынести из этой книги?",
    goalPlaceholder: "Понять главный аргумент автора настолько, чтобы объяснить его другу.",
    goalHelp: "Ассистент видит эту цель в каждом разговоре внутри этой книги.",
    remember: "Также предложить эту цель для долговременной памяти",
    save: "Сохранить цель",
    clear: "Удалить цель",
    noBook: "Откройте книгу, чтобы задать для неё цель чтения.",
    invalid: "Введите цель длиной от 1 до 500 символов.",
    refresh: "Обновить",
    saved: "Цель сохранена",
    cleared: "Цель удалена",
    conflict: "Эта цель была изменена в другом месте. Обновите и попробуйте снова.",
    confirm: "Удалить цель чтения для этой книги",
    required: "Сначала подтвердите удаление.",
    memoryOff: "Долговременная память выключена в «Настройки → ИИ»; пока она выключена, цель не будет предлагаться для памяти.",
    bookMissing: "Этой книги больше нет в вашей библиотеке.",
  },
};
export function copy(locale: string): Copy {
  return copies[locale] ?? copies[locale.split("-")[0]!] ?? (locale.startsWith("zh") ? copies["zh-Hans"]! : en);
}
