const en = {
  repair: "Repair local projections", "rebuilt-reload-required": "Projections rebuilt; reload required",
  repairReview: "The host previews differences and requires your confirmation. Repair replays the complete local event log and discards projection-only changes. Writes then pause until app reload. Cancelling this wait cannot undo a confirmed repair.",
  title: "Maintenance Desk", catalog: "Model catalog", provider: "Catalog provider", search: "Search models",
  syncNow: "Synchronize now", syncConnect: "Connect synchronization", syncDisconnect: "Disconnect synchronization",
  syncDelete: "Delete Relay account", syncUpgrade: "Choose a plan", syncBilling: "Manage billing",
  syncCycleCompleted: "Synchronization request completed", syncAlreadyRunning: "A synchronization was already running",
  syncFlowCompleted: "Native account operation completed", syncExternalOpened: "External page opened; account changes not verified",
  browse: "Browse", refresh: "Refresh from provider", reload: "Reload cached catalog", filters: "Change filters",
  empty: "No matching models", invalidSearch: "Use at most 120 characters.", invalidProvider: "Choose a catalog provider.",
  metadata: "Catalog status", checked: "Last checked", never: "Not checked", refreshing: "Refreshing", yes: "Yes", no: "No",
  matches: "Matching models", context: "Context window", output: "Maximum output tokens", input: "Input", reasoning: "Reasoning",
  connection: "Test AI connection", backupExport: "Export backup", backupImport: "Import backup",
  reportExport: "Export diagnostic report", reportSend: "Send diagnostic report", verify: "Verify local projections",
  continue: "Continue", results: "Recent operations", noResults: "No operations in this session", pending: "Awaiting host result",
  cancelling: "Cancelling wait", cancel: "Cancel wait", cancelled: "Wait cancelled; started operations may continue",
  busy: "An operation is still awaiting a result.", complete: "Completed", failed: "Failed", clear: "Clear finished operations",
  back: "Maintenance Desk", responded: "Non-empty test response", emptyResponse: "Empty test response",
  exported: "Exported", imported: "Imported", sent: "Report endpoint acknowledged receipt",
  consistent: "Projections consistent", drifted: "Projection differences found", events: "Events replayed",
  tables: "Drifted tables", liveRows: "Rows only in live projections", replayRows: "Rows only in replayed projections",
  connectionReview: "The native Test connection button uses the current primary-model configuration. A test may incur provider charges. A response does not verify saved settings or every model feature.",
  backupReview: "Choose a complete encrypted archive or a legacy library backup in the host settings. The host explains each format's contents and handles the password and file selection. Backup data can include personal information.",
  importReview: "Complete archives require a password, restore choices and confirmation, then an app reload. Legacy library imports merge records and can partially apply before failure. Cancelling this wait cannot undo committed changes; restarting can discard this session's result.",
  reportReview: "Diagnostic reports may contain personal data. The host provides the report preview and final export or send confirmation. A sent receipt does not mean a developer has reviewed it.",
  verifyReview: "Checks event-log projections on this device only. This does not repair data or verify backups and other devices.",
};
const zh: typeof en = {
  repair: "修复本机投影", "rebuilt-reload-required": "投影已重建；需要重新载入",
  repairReview: "宿主将显示差异并要求确认。修复按完整事件日志重建本机投影，丢弃仅存在于投影的修改，之后暂停写入直至重新载入应用。取消等待不能撤销已确认的修复。",
  title: "维护工作台", catalog: "模型目录", provider: "目录提供者", search: "搜索模型",
  syncNow: "立即同步", syncConnect: "连接同步", syncDisconnect: "断开同步",
  syncDelete: "删除 Relay 账户", syncUpgrade: "选择套餐", syncBilling: "管理账单",
  syncCycleCompleted: "同步请求已完成", syncAlreadyRunning: "已有同步正在运行",
  syncFlowCompleted: "原生账户操作已完成", syncExternalOpened: "已打开外部页面；未验证账户变更",
  browse: "查看", refresh: "从提供者刷新", reload: "重新读取缓存目录", filters: "修改筛选",
  empty: "没有匹配的模型", invalidSearch: "最多输入 120 个字符。", invalidProvider: "请选择目录提供者。",
  metadata: "目录状态", checked: "上次检查", never: "尚未检查", refreshing: "正在刷新", yes: "是", no: "否",
  matches: "匹配模型数", context: "上下文窗口", output: "最大输出 token", input: "输入类型", reasoning: "推理支持",
  connection: "测试 AI 连接", backupExport: "导出备份", backupImport: "导入备份",
  reportExport: "导出诊断报告", reportSend: "发送诊断报告", verify: "校验本机投影",
  continue: "继续", results: "近期操作", noResults: "本次会话暂无操作", pending: "等待宿主结果",
  cancelling: "正在取消等待", cancel: "取消等待", cancelled: "等待已取消；已开始的操作可能继续",
  busy: "仍有操作在等待结果。", complete: "已完成", failed: "失败", clear: "清除已结束的记录",
  back: "维护工作台", responded: "测试返回了非空回复", emptyResponse: "测试返回了空回复",
  exported: "已导出", imported: "已导入", sent: "报告接口已确认收件",
  consistent: "投影一致", drifted: "发现投影差异", events: "重放事件数",
  tables: "差异表数", liveRows: "仅存在于当前投影的行数", replayRows: "仅存在于重放投影的行数",
  connectionReview: "原生连接测试使用当前主模型配置，可能产生提供者费用。收到回复不代表配置已保存或全部模型功能可用。",
  backupReview: "在宿主设置中选择完整加密归档或旧版书库备份。宿主会说明各格式包含的内容，并处理密码与文件选择。备份可能包含个人资料。",
  importReview: "完整归档需输入密码、选择恢复内容并确认，完成后重新载入应用。旧版书库导入会合并记录，可能在部分写入后失败。取消等待不能撤销已提交的修改；重启可能丢失本次会话的结果记录。",
  reportReview: "诊断报告可能含个人数据，由宿主提供报告预览与最终导出或发送确认。发送回执不代表开发者已处理。",
  verifyReview: "仅校验本设备的事件日志投影，不修复数据，也不验证备份或其他设备。",
};
export const copy = (locale: string) => locale.startsWith("zh") ? zh : en;
export type Copy = typeof en;
