const en = {
  title: "Workspace Profiles",
  description: "Save the current shelf, appearance and reading setup as a named profile and switch between them.",
  save: "Save current workspace",
  name: "Profile name",
  namePlaceholder: "Evening reading",
  invalid: "Enter a name of 1–80 characters.",
  empty: "No profiles yet. Save the current workspace to create one.",
  apply: "Apply",
  rename: "Rename",
  remove: "Delete",
  refresh: "Refresh",
  saved: "Profile saved",
  renamed: "Profile renamed",
  applied: "Profile applied",
  undo: "Undo",
  undone: "Previous settings restored",
  conflict: "This profile or your settings changed in the meantime. Reload and try again.",
  missing: "This profile no longer exists.",
  invalidProfile: "Unreadable profile",
  stalePage: "The profile list changed. Reload it.",
  confirmDelete: "Delete this profile permanently",
  confirmRequired: "Confirm the deletion first.",
  deleted: "Profile deleted",
  appDefault: "App default",
  on: "On",
  off: "Off",
  savedAt: "Saved",
  settings: "Settings",
  back: "All profiles",
};
type Copy = typeof en;
const translations: Record<string, Copy> = {
  en,
  "zh-Hans": {
    title: "工作区预设",
    description: "把当前书架、外观和阅读设置保存为一个命名预设，随时切换。",
    save: "保存当前工作区",
    name: "预设名称",
    namePlaceholder: "夜间阅读",
    invalid: "请输入 1–80 个字符的名称。",
    empty: "还没有预设。保存当前工作区即可创建。",
    apply: "应用",
    rename: "重命名",
    remove: "删除",
    refresh: "刷新",
    saved: "预设已保存",
    renamed: "预设已重命名",
    applied: "预设已应用",
    undo: "撤销",
    undone: "已恢复之前的设置",
    conflict: "预设或你的设置在此期间有变化，请刷新后再试。",
    missing: "这个预设已不存在。",
    invalidProfile: "无法读取的预设",
    stalePage: "预设列表已变化，请刷新。",
    confirmDelete: "永久删除这个预设",
    confirmRequired: "请先确认删除。",
    deleted: "预设已删除",
    appDefault: "应用默认",
    on: "开",
    off: "关",
    savedAt: "保存于",
    settings: "设置",
    back: "全部预设",
  },
  "zh-Hant": {
    title: "工作區預設",
    description: "把目前書架、外觀和閱讀設定儲存為一個命名預設，隨時切換。",
    save: "儲存目前工作區",
    name: "預設名稱",
    namePlaceholder: "夜間閱讀",
    invalid: "請輸入 1–80 個字元的名稱。",
    empty: "還沒有預設。儲存目前工作區即可建立。",
    apply: "套用",
    rename: "重新命名",
    remove: "刪除",
    refresh: "重新整理",
    saved: "預設已儲存",
    renamed: "預設已重新命名",
    applied: "預設已套用",
    undo: "復原",
    undone: "已恢復先前的設定",
    conflict: "預設或你的設定在此期間有變化，請重新整理後再試。",
    missing: "這個預設已不存在。",
    invalidProfile: "無法讀取的預設",
    stalePage: "預設清單已變化，請重新整理。",
    confirmDelete: "永久刪除這個預設",
    confirmRequired: "請先確認刪除。",
    deleted: "預設已刪除",
    appDefault: "應用程式預設",
    on: "開",
    off: "關",
    savedAt: "儲存於",
    settings: "設定",
    back: "全部預設",
  },
  ja: {
    title: "ワークスペースプロファイル",
    description: "現在の本棚・外観・読書設定に名前を付けて保存し、いつでも切り替えられます。",
    save: "現在のワークスペースを保存",
    name: "プロファイル名",
    namePlaceholder: "夜の読書",
    invalid: "1〜80文字の名前を入力してください。",
    empty: "プロファイルはまだありません。現在のワークスペースを保存して作成します。",
    apply: "適用",
    rename: "名前を変更",
    remove: "削除",
    refresh: "更新",
    saved: "プロファイルを保存しました",
    renamed: "プロファイル名を変更しました",
    applied: "プロファイルを適用しました",
    undo: "元に戻す",
    undone: "以前の設定に戻しました",
    conflict: "その間にプロファイルまたは設定が変更されました。再読み込みしてやり直してください。",
    missing: "このプロファイルはもう存在しません。",
    invalidProfile: "読み取れないプロファイル",
    stalePage: "プロファイル一覧が変わりました。再読み込みしてください。",
    confirmDelete: "このプロファイルを完全に削除する",
    confirmRequired: "先に削除を確認してください。",
    deleted: "プロファイルを削除しました",
    appDefault: "アプリの既定",
    on: "オン",
    off: "オフ",
    savedAt: "保存日時",
    settings: "設定",
    back: "すべてのプロファイル",
  },
  de: {
    title: "Arbeitsbereich-Profile",
    description: "Speichern Sie Regal, Erscheinungsbild und Leseeinstellungen als benanntes Profil und wechseln Sie jederzeit.",
    save: "Aktuellen Arbeitsbereich speichern",
    name: "Profilname",
    namePlaceholder: "Abendlektüre",
    invalid: "Geben Sie einen Namen mit 1–80 Zeichen ein.",
    empty: "Noch keine Profile. Speichern Sie den aktuellen Arbeitsbereich, um eines anzulegen.",
    apply: "Anwenden",
    rename: "Umbenennen",
    remove: "Löschen",
    refresh: "Aktualisieren",
    saved: "Profil gespeichert",
    renamed: "Profil umbenannt",
    applied: "Profil angewendet",
    undo: "Rückgängig",
    undone: "Vorherige Einstellungen wiederhergestellt",
    conflict: "Das Profil oder Ihre Einstellungen haben sich inzwischen geändert. Laden Sie neu und versuchen Sie es erneut.",
    missing: "Dieses Profil existiert nicht mehr.",
    invalidProfile: "Unlesbares Profil",
    stalePage: "Die Profilliste hat sich geändert. Laden Sie sie neu.",
    confirmDelete: "Dieses Profil dauerhaft löschen",
    confirmRequired: "Bestätigen Sie zuerst das Löschen.",
    deleted: "Profil gelöscht",
    appDefault: "App-Standard",
    on: "Ein",
    off: "Aus",
    savedAt: "Gespeichert",
    settings: "Einstellungen",
    back: "Alle Profile",
  },
  fr: {
    title: "Profils d’espace de travail",
    description: "Enregistrez l’étagère, l’apparence et les réglages de lecture actuels sous un nom et passez de l’un à l’autre.",
    save: "Enregistrer l’espace de travail actuel",
    name: "Nom du profil",
    namePlaceholder: "Lecture du soir",
    invalid: "Saisissez un nom de 1 à 80 caractères.",
    empty: "Aucun profil pour l’instant. Enregistrez l’espace de travail actuel pour en créer un.",
    apply: "Appliquer",
    rename: "Renommer",
    remove: "Supprimer",
    refresh: "Actualiser",
    saved: "Profil enregistré",
    renamed: "Profil renommé",
    applied: "Profil appliqué",
    undo: "Annuler",
    undone: "Réglages précédents restaurés",
    conflict: "Le profil ou vos réglages ont changé entre-temps. Rechargez et réessayez.",
    missing: "Ce profil n’existe plus.",
    invalidProfile: "Profil illisible",
    stalePage: "La liste des profils a changé. Rechargez-la.",
    confirmDelete: "Supprimer définitivement ce profil",
    confirmRequired: "Confirmez d’abord la suppression.",
    deleted: "Profil supprimé",
    appDefault: "Valeur par défaut",
    on: "Activé",
    off: "Désactivé",
    savedAt: "Enregistré",
    settings: "Réglages",
    back: "Tous les profils",
  },
  es: {
    title: "Perfiles de espacio de trabajo",
    description: "Guarda la estantería, la apariencia y los ajustes de lectura actuales con un nombre y cambia entre ellos cuando quieras.",
    save: "Guardar espacio de trabajo actual",
    name: "Nombre del perfil",
    namePlaceholder: "Lectura nocturna",
    invalid: "Escribe un nombre de 1 a 80 caracteres.",
    empty: "Aún no hay perfiles. Guarda el espacio de trabajo actual para crear uno.",
    apply: "Aplicar",
    rename: "Renombrar",
    remove: "Eliminar",
    refresh: "Actualizar",
    saved: "Perfil guardado",
    renamed: "Perfil renombrado",
    applied: "Perfil aplicado",
    undo: "Deshacer",
    undone: "Ajustes anteriores restaurados",
    conflict: "El perfil o tus ajustes cambiaron mientras tanto. Recarga e inténtalo de nuevo.",
    missing: "Este perfil ya no existe.",
    invalidProfile: "Perfil ilegible",
    stalePage: "La lista de perfiles cambió. Recárgala.",
    confirmDelete: "Eliminar este perfil de forma permanente",
    confirmRequired: "Confirma primero la eliminación.",
    deleted: "Perfil eliminado",
    appDefault: "Valor predeterminado",
    on: "Activado",
    off: "Desactivado",
    savedAt: "Guardado",
    settings: "Ajustes",
    back: "Todos los perfiles",
  },
  ru: {
    title: "Профили рабочего пространства",
    description: "Сохраните текущие настройки полки, оформления и чтения как именованный профиль и переключайтесь между ними.",
    save: "Сохранить текущее пространство",
    name: "Название профиля",
    namePlaceholder: "Вечернее чтение",
    invalid: "Введите название длиной от 1 до 80 символов.",
    empty: "Профилей пока нет. Сохраните текущее пространство, чтобы создать первый.",
    apply: "Применить",
    rename: "Переименовать",
    remove: "Удалить",
    refresh: "Обновить",
    saved: "Профиль сохранён",
    renamed: "Профиль переименован",
    applied: "Профиль применён",
    undo: "Отменить",
    undone: "Прежние настройки восстановлены",
    conflict: "Профиль или ваши настройки тем временем изменились. Обновите и попробуйте снова.",
    missing: "Этого профиля больше нет.",
    invalidProfile: "Нечитаемый профиль",
    stalePage: "Список профилей изменился. Обновите его.",
    confirmDelete: "Удалить этот профиль навсегда",
    confirmRequired: "Сначала подтвердите удаление.",
    deleted: "Профиль удалён",
    appDefault: "По умолчанию",
    on: "Вкл.",
    off: "Выкл.",
    savedAt: "Сохранено",
    settings: "Настройки",
    back: "Все профили",
  },
};

export const copy = (locale: string): Copy =>
  translations[locale] ?? translations[locale.split("-")[0]!] ?? (locale.startsWith("zh") ? translations["zh-Hans"]! : en);
